(() => {
  let db=StoreDB.load();
  let cart=JSON.parse(localStorage.getItem(StoreDB.CART_KEY)||'[]');
  let wishlist=JSON.parse(localStorage.getItem(StoreDB.WISH_KEY)||'[]');
  let customer=null;
  let checkoutItems=[];
  let readyResolve;
  const ready=new Promise(r=>readyResolve=r);
  const districts=['Ampara','Anuradhapura','Badulla','Batticaloa','Colombo','Galle','Gampaha','Hambantota','Jaffna','Kalutara','Kandy','Kegalle','Kilinochchi','Kurunegala','Mannar','Matale','Matara','Monaragala','Mullaitivu','Nuwara Eliya','Polonnaruwa','Puttalam','Ratnapura','Trincomalee','Vavuniya'];
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const money=StoreDB.money;
  const productById=id=>db.products.find(p=>p.id===id);
  const available=p=>p&&p.status==='published'&&p.stock!=='out'&&(p.qty===999||Number(p.qty)>0);
  const mainImage=p=>p?.media?.images?.[0]||'';
  const approvedReviews=id=>db.reviews.filter(r=>r.productId===id&&r.status==='approved');
  const ratingInfo=id=>{const list=approvedReviews(id);return {count:list.length,avg:list.length?list.reduce((a,r)=>a+Number(r.rating||0),0)/list.length:0}};
  const discountPct=p=>p.oldPrice>p.price?Math.round((p.oldPrice-p.price)/p.oldPrice*100):0;

  function saveLocal(){localStorage.setItem(StoreDB.CART_KEY,JSON.stringify(cart));localStorage.setItem(StoreDB.WISH_KEY,JSON.stringify(wishlist));}
  async function refresh(){db=await StoreDB.loadPublic();return db;}
  function toast(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),3000)}
  function openLayer(id){const el=document.getElementById(id);if(el){el.classList.add('open');document.body.classList.add('no-scroll')}}
  function closeLayer(id){const el=document.getElementById(id);if(el){el.classList.remove('open');if(!document.querySelector('.modal.open,.drawer.open'))document.body.classList.remove('no-scroll')}}
  function fillDistricts(){const el=$('#districtSelect');if(el)el.innerHTML='<option value="">Select district</option>'+districts.map(d=>`<option>${d}</option>`).join('')}

  function updateCounts(){const c=cart.reduce((a,x)=>a+Number(x.qty||0),0);$$('#cartCount').forEach(el=>el.textContent=c);$$('#wishlistCount').forEach(el=>el.textContent=wishlist.length)}
  function addToCart(id,qty=1){const p=productById(id);if(!available(p)){toast('This product is currently unavailable.');return}const found=cart.find(x=>x.productId===id);if(found)found.qty+=qty;else cart.push({productId:id,qty});saveLocal();updateCounts();renderCart();toast('Added to cart')}
  function toggleWishlist(id){const i=wishlist.indexOf(id);if(i>=0)wishlist.splice(i,1);else wishlist.push(id);saveLocal();updateCounts();renderWishlist();if(typeof window.renderStoreProducts==='function')window.renderStoreProducts();toast(i>=0?'Removed from wishlist':'Saved to wishlist')}
  function cartLines(){return cart.map(x=>{const p=productById(x.productId);return p?{...x,p}:null}).filter(Boolean)}
  function renderCart(){const wrap=$('#cartItems'),tot=$('#cartTotals');if(!wrap||!tot)return;const lines=cartLines();if(!lines.length){wrap.innerHTML='<div class="empty-mini">🛒<h3>Your cart is empty</h3><p>Add a product to continue.</p></div>';tot.innerHTML='';return}wrap.innerHTML=lines.map(({p,qty})=>`<div class="cart-line"><div class="cart-thumb">${mainImage(p)?`<img src="${esc(mainImage(p))}" alt="${esc(p.name)}">`:'<span>🛍️</span>'}</div><div><a href="product.html?id=${encodeURIComponent(p.id)}"><b>${esc(p.name)}</b></a><small>${money(p.price)}</small><div class="qty-row"><button data-dec="${p.id}">−</button><span>${qty}</span><button data-inc="${p.id}">+</button><button class="link-danger" data-remove="${p.id}">Remove</button></div></div><strong>${money(p.price*qty)}</strong></div>`).join('');const subtotal=lines.reduce((a,x)=>a+x.p.price*x.qty,0);tot.innerHTML=`<div class="cart-summary"><div><span>Subtotal</span><b>${money(subtotal)}</b></div><div><span>Payment</span><b>Cash on Delivery</b></div><button class="primary-btn full-btn" id="checkoutCartBtn">Checkout</button></div>`;$$('[data-inc]').forEach(b=>b.onclick=()=>{cart.find(x=>x.productId===b.dataset.inc).qty++;saveLocal();renderCart();updateCounts()});$$('[data-dec]').forEach(b=>b.onclick=()=>{const x=cart.find(x=>x.productId===b.dataset.dec);x.qty--;if(x.qty<=0)cart=cart.filter(y=>y.productId!==x.productId);saveLocal();renderCart();updateCounts()});$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.productId!==b.dataset.remove);saveLocal();renderCart();updateCounts()});$('#checkoutCartBtn').onclick=()=>startCheckout(lines.map(x=>({productId:x.p.id,qty:x.qty})))}
  function renderWishlist(){const wrap=$('#wishlistItems');if(!wrap)return;const items=wishlist.map(productById).filter(Boolean);wrap.innerHTML=items.length?items.map(p=>`<div class="wishlist-line"><a href="product.html?id=${encodeURIComponent(p.id)}"><div class="cart-thumb">${mainImage(p)?`<img src="${esc(mainImage(p))}">`:'🛍️'}</div><div><b>${esc(p.name)}</b><small>${money(p.price)}</small></div></a><button class="close-btn" data-unwish="${p.id}">✕</button></div>`).join(''):'<div class="empty-mini">♡<h3>No saved products</h3><p>Tap the heart on products you like.</p></div>';$$('[data-unwish]').forEach(b=>b.onclick=()=>toggleWishlist(b.dataset.unwish))}

  function startCheckout(items){checkoutItems=items.map(x=>({productId:x.productId,qty:Number(x.qty||1)})).filter(x=>available(productById(x.productId)));if(!checkoutItems.length){toast('No available products to checkout.');return}closeLayer('cartDrawer');const form=$('#checkoutForm');if(form&&customer){form.elements.name.value=customer.name||'';form.elements.phone.value=customer.phone||'';form.elements.email.value=customer.email||''}renderCheckoutSummary();openLayer('checkoutModal')}
  function renderCheckoutSummary(){const wrap=$('#checkoutSummary');if(!wrap)return;const lines=checkoutItems.map(x=>({p:productById(x.productId),qty:x.qty})).filter(x=>x.p);const subtotal=lines.reduce((a,x)=>a+x.p.price*x.qty,0);wrap.innerHTML=`<h3>Order Summary</h3>${lines.map(x=>`<div class="summary-line"><span>${esc(x.p.name)} × ${x.qty}</span><b>${money(x.p.price*x.qty)}</b></div>`).join('')}<div class="summary-line total"><span>Total</span><b>${money(subtotal)}</b></div><div class="cod-pill">💵 Cash on Delivery</div>`}
  async function submitCheckout(e){
    e.preventDefault();const btn=e.currentTarget.querySelector('button[type=submit],button:not([type])');if(btn){btn.disabled=true;btn.textContent='Placing Order...'}
    try{
      const f=new FormData(e.currentTarget);
      const customerData={name:f.get('name').trim(),phone:f.get('phone').trim(),altPhone:f.get('altPhone').trim(),email:f.get('email').trim(),address:f.get('address').trim(),city:f.get('city').trim(),district:f.get('district'),landmark:f.get('landmark').trim(),notes:f.get('notes').trim()};
      const result=await StoreDB.placeOrder(customerData,checkoutItems);
      cart=cart.filter(c=>!checkoutItems.some(x=>x.productId===c.productId));saveLocal();updateCounts();renderCart();closeLayer('checkoutModal');
      const details=$('#successDetails');if(details)details.innerHTML=`<div><span>Order Number</span><b>${esc(result.orderNumber)}</b></div><div><span>Total</span><b>${money(result.total)}</b></div><div><span>Payment</span><b>Cash on Delivery</b></div>`;
      openLayer('successModal');e.currentTarget.reset();checkoutItems=[];toast('Order placed successfully');
    }catch(err){toast(err.message||'Could not place order. Please try again.')}finally{if(btn){btn.disabled=false;btn.textContent='Place Cash on Delivery Order'}}
  }

  async function loadCustomer(){
    try{const u=await StoreDB.currentUser();if(u){customer={id:u.id,name:u.user_metadata?.name||u.email?.split('@')[0]||'Customer',email:u.email||'',phone:u.user_metadata?.phone||''}}else customer=null}catch{customer=null}
  }
  function renderAccount(){
    const el=$('#accountContent');if(!el)return;
    if(customer){el.innerHTML=`<div class="account-card"><div class="account-avatar">${esc((customer.name||'C').charAt(0).toUpperCase())}</div><h3>${esc(customer.name)}</h3><p>${esc(customer.email||customer.phone||'')}</p><div class="guest-note">Your account is optional. Guest checkout remains available.</div><div class="account-actions"><button class="outline-btn full-btn" id="logoutBtn">Log Out</button></div></div>`;$('#logoutBtn').onclick=async()=>{await StoreDB.signOut();customer=null;renderAccount();toast('Logged out')};return;
    }
    el.innerHTML=`<div class="guest-note">Creating an account is optional. You can always place an order as a guest.</div><button class="google-login-btn full-btn" id="googleLoginBtn">G&nbsp; Continue with Google</button><div class="account-divider"><span>or</span></div><div class="account-tabs"><button class="active" data-account-tab="login">Login</button><button data-account-tab="register">Create Account</button></div><form id="loginForm"><label class="field"><span>Email</span><input name="email" type="email" required></label><label class="field"><span>Password</span><input type="password" name="password" required></label><button class="primary-btn full-btn">Login</button></form><form id="registerForm" class="hidden"><label class="field"><span>Name</span><input name="name" required></label><label class="field"><span>Email</span><input type="email" name="email" required></label><label class="field"><span>Phone (optional)</span><input name="phone" inputmode="tel"></label><label class="field"><span>Password</span><input type="password" name="password" minlength="6" required></label><button class="primary-btn full-btn">Create Account</button></form>`;
    $$('[data-account-tab]').forEach(b=>b.onclick=()=>{$$('[data-account-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',b.dataset.accountTab!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.accountTab!=='register')});
    $('#googleLoginBtn').onclick=()=>StoreDB.signInGoogle().catch(e=>toast(e.message));
    $('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await StoreDB.signInCustomer(f.get('email').trim(),f.get('password'));await loadCustomer();renderAccount();toast('Welcome back')}catch(err){toast(err.message)}};
    $('#registerForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const data=await StoreDB.signUpCustomer(f.get('name').trim(),f.get('email').trim(),f.get('password'),f.get('phone').trim());if(data.session){await loadCustomer();renderAccount();toast('Account created')}else toast('Account created. Check your email if confirmation is enabled.')}catch(err){toast(err.message)}};
  }

  function renderHome(){if(!$('#productGrid'))return;const cats=db.categories,cg=$('#categoryGrid');if(cg){cg.innerHTML=cats.length?cats.map((c,i)=>`<button class="category-card" data-category="${esc(c)}"><span class="cat-emoji">${['✦','⌂','♡','⚡','☼','♢'][i%6]}</span><span><small>Explore</small><b>${esc(c)}</b></span><span>→</span></button>`).join(''):'<div class="empty-inline">No categories yet — they will appear after you create them in Admin.</div>';$$('[data-category]').forEach(b=>b.onclick=()=>{if($('#categoryFilter'))$('#categoryFilter').value=b.dataset.category;renderStoreProducts();location.hash='#shop'})}const cf=$('#categoryFilter');if(cf)cf.innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');renderStoreProducts();renderOffers();if($('#footerEmail'))$('#footerEmail').textContent=db.settings.email||'hello@stepinstyle.lk'}
  function filteredProducts(){const q=($('#searchInput')?.value||'').trim().toLowerCase(),cat=$('#categoryFilter')?.value||'',sort=$('#sortFilter')?.value||'featured';let list=db.products.filter(p=>p.status==='published'&&(!q||[p.name,p.category,p.shortDescription].join(' ').toLowerCase().includes(q))&&(!cat||p.category===cat));if(sort==='priceLow')list.sort((a,b)=>a.price-b.price);else if(sort==='priceHigh')list.sort((a,b)=>b.price-a.price);else if(sort==='popular')list.sort((a,b)=>b.views-a.views);else if(sort==='newest')list.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));else list.sort((a,b)=>Number(b.featured)-Number(a.featured));return list}
  function productCard(p){const r=ratingInfo(p.id),d=discountPct(p),wish=wishlist.includes(p.id);return `<article class="product-card"><a class="product-image-link" href="product.html?id=${encodeURIComponent(p.id)}"><div class="product-img">${mainImage(p)?`<img src="${esc(mainImage(p))}" alt="${esc(p.name)}">`:'<div class="image-placeholder">Step in Style</div>'}${p.badge||d?`<span class="product-badge">${esc(p.badge||d+'% OFF')}</span>`:''}</div></a><button class="wish-btn ${wish?'active':''}" data-wish="${p.id}">${wish?'♥':'♡'}</button><div class="product-body"><span class="product-cat">${esc(p.category||'Product')}</span><a class="product-title" href="product.html?id=${encodeURIComponent(p.id)}">${esc(p.name)}</a><div class="card-rating">${r.count?`<span class="stars">${'★'.repeat(Math.round(r.avg))}</span> ${r.avg.toFixed(1)} <small>(${r.count})</small>`:'<small>No reviews yet</small>'}</div><div class="price-line"><span class="price">${money(p.price)}</span>${p.oldPrice>p.price?`<del>${money(p.oldPrice)}</del>`:''}</div><div class="availability ${p.stock}">${p.stock==='out'?'● Out of Stock':p.stock==='limited'?'● Limited Availability':'● Available'}</div><div class="product-actions"><a class="outline-btn small" href="product.html?id=${encodeURIComponent(p.id)}">View Product</a><button class="primary-btn small" data-cart="${p.id}" ${!available(p)?'disabled':''}>Add</button></div></div></article>`}
  function renderStoreProducts(){const list=filteredProducts(),grid=$('#productGrid'),emptyEl=$('#productEmpty');if(!grid)return;grid.innerHTML=list.map(productCard).join('');emptyEl?.classList.toggle('hidden',db.products.filter(p=>p.status==='published').length>0);if(list.length===0&&db.products.some(p=>p.status==='published'))grid.innerHTML='<div class="empty-inline full-span">No products match your search.</div>';$$('[data-wish]').forEach(b=>b.onclick=()=>toggleWishlist(b.dataset.wish));$$('[data-cart]').forEach(b=>b.onclick=()=>addToCart(b.dataset.cart))}
  function renderOffers(){const sec=$('#offers'),grid=$('#offerGrid');if(!sec||!grid)return;const now=new Date(),offers=db.offers.filter(o=>o.active!==false&&(!o.start||new Date(o.start+'T00:00:00')<=now)&&(!o.end||new Date(o.end+'T23:59:59')>=now));sec.classList.toggle('hidden',offers.length===0);grid.innerHTML=offers.map(o=>`<article class="offer-card"><span>STEP IN STYLE OFFER</span><h3>${esc(o.name)}</h3><p>${o.type==='percent'?`${Number(o.value)}% off selected products`:`Save ${money(o.value)}`}</p><a class="light-btn" href="#shop">Shop Offer</a></article>`).join('')}

  function bind(){updateCounts();renderCart();renderWishlist();renderAccount();fillDistricts();$$('#cartBtn,#mobileCart').forEach(b=>b.onclick=()=>{renderCart();openLayer('cartDrawer')});$('#wishlistBtn')&&($('#wishlistBtn').onclick=()=>{renderWishlist();openLayer('wishlistDrawer')});$$('#accountBtn,#mobileAccount').forEach(b=>b.onclick=()=>{renderAccount();openLayer('accountModal')});$$('[data-close]').forEach(b=>b.onclick=()=>closeLayer(b.dataset.close));$('#checkoutForm')&&($('#checkoutForm').onsubmit=submitCheckout);$('#searchInput')&&($('#searchInput').oninput=renderStoreProducts);$('#categoryFilter')&&($('#categoryFilter').onchange=renderStoreProducts);$('#sortFilter')&&($('#sortFilter').onchange=renderStoreProducts);$('#clearFilters')&&($('#clearFilters').onclick=()=>{$('#searchInput').value='';$('#categoryFilter').value='';$('#sortFilter').value='featured';renderStoreProducts()})}

  window.ShopApp={ready,addToCart,toggleWishlist,startCheckout,openLayer,closeLayer,toast,refresh,productById,mainImage,approvedReviews,ratingInfo,available,money,esc,getDB:()=>db,getCustomer:()=>customer,getWishlist:()=>wishlist};
  window.renderStoreProducts=renderStoreProducts;
  document.addEventListener('DOMContentLoaded',async()=>{
    bind();
    try{await Promise.all([refresh(),loadCustomer()]);renderAccount();renderHome();readyResolve(true)}catch(err){readyResolve(false);toast(err.message);const grid=$('#productGrid');if(grid)grid.innerHTML=`<div class="setup-warning full-span"><h3>Connect Supabase to activate the store</h3><p>${esc(err.message)}</p><p>Follow <b>SUPABASE_SETUP.md</b> included in the ZIP.</p></div>`}
    if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('service-worker.js').catch(()=>{});
  });
})();
