(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>ShopApp.esc(s), money=ShopApp.money;
  let product=null, activeMedia=0, reviewImageFiles=[], reviewVideoFile=null;
  const params=new URLSearchParams(location.search), id=params.get('id'), preview=params.get('preview')==='1';

  function ytEmbed(url){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return 'https://www.youtube.com/embed/'+u.pathname.slice(1);if(u.hostname.includes('youtube.com')){const v=u.searchParams.get('v');if(v)return 'https://www.youtube.com/embed/'+v;const m=u.pathname.match(/\/embed\/([^/]+)/);if(m)return 'https://www.youtube.com/embed/'+m[1]}}catch{}return ''}
  function videoHtml(src,cls='detail-video'){const yt=ytEmbed(src);return yt?`<iframe class="${cls}" src="${esc(yt)}" allowfullscreen loading="lazy" title="Product video"></iframe>`:`<video class="${cls}" src="${esc(src)}" controls playsinline preload="metadata"></video>`}
  function linebreak(s){return esc(s).replace(/\n/g,'<br>')}
  function renderDescription(p){const b=p.descriptionBlocks||[];if(!b.length)return '<div class="description-empty"><p>More product information will be added soon.</p></div>';return `<div class="rich-description">${b.map(x=>{if(x.type==='heading')return `<h2>${esc(x.content||'')}</h2>`;if(x.type==='text')return `<div class="rich-text">${x.html||linebreak(x.content||'')}</div>`;if(x.type==='image'&&x.src)return `<figure><img src="${esc(x.src)}" alt="${esc(x.caption||p.name)}"><figcaption>${esc(x.caption||'')}</figcaption></figure>`;if(x.type==='video'&&x.src)return `<figure>${videoHtml(x.src,'description-video')}<figcaption>${esc(x.caption||'')}</figcaption></figure>`;if(x.type==='features'){const lines=String(x.content||'').split('\n').filter(Boolean);return `<div class="feature-block"><h3>${esc(x.title||'Main Features')}</h3><ul>${lines.map(v=>`<li>✓ ${esc(v.replace(/^[-•✓]\s*/,''))}</li>`).join('')}</ul></div>`}if(x.type==='specs'){const lines=String(x.content||'').split('\n').filter(Boolean);return `<div class="spec-block"><h3>${esc(x.title||'Specifications')}</h3><div class="spec-table">${lines.map(v=>{const [k,...rest]=v.split(':');return `<div><b>${esc(k||'')}</b><span>${esc(rest.join(':').trim()||'—')}</span></div>`}).join('')}</div></div>`}return ''}).join('')}</div>`}
  function approvedReviews(){return ShopApp.getDB().reviews.filter(r=>r.productId===product.id&&r.status==='approved')}
  function reviewMedia(r){const imgs=(r.media?.images||[]).map(src=>`<button class="review-media-thumb" data-lightbox="${esc(src)}"><img src="${esc(src)}" alt="Customer review photo"></button>`).join('');const vids=(r.media?.videos||[]).map(src=>`<div class="review-video-wrap">${videoHtml(src,'review-video')}</div>`).join('');return imgs||vids?`<div class="review-media">${imgs}${vids}</div>`:''}
  function reviewCard(r){return `<article class="review-card"><div class="review-head"><div><span class="stars">${'★'.repeat(Number(r.rating||0))}${'☆'.repeat(5-Number(r.rating||0))}</span><div><b>${esc(r.name)}</b>${r.verified?'<em>✓ Verified Purchase</em>':''}</div></div><small>${esc(r.date||'')}</small></div><p>${linebreak(r.text||'')}</p>${reviewMedia(r)}${r.reply?`<div class="admin-reply"><b>Step in Style replied</b><p>${linebreak(r.reply)}</p></div>`:''}</article>`}
  function renderReviews(){const list=approvedReviews(),wrap=$('#reviewsList'),summary=$('#reviewSummary');const avg=list.length?list.reduce((a,r)=>a+Number(r.rating||0),0)/list.length:0;summary.innerHTML=list.length?`<div><strong>${avg.toFixed(1)}</strong><span class="stars">${'★'.repeat(Math.round(avg))}${'☆'.repeat(5-Math.round(avg))}</span><small>Based on ${list.length} approved review${list.length===1?'':'s'}</small></div><button class="primary-btn" id="writeReviewBtn">Write a Review</button>`:`<div><strong>New</strong><span>No reviews yet</span><small>Be the first to review this product.</small></div><button class="primary-btn" id="writeReviewBtn">Write a Review</button>`;wrap.innerHTML=list.length?list.map(reviewCard).join(''):'<div class="empty-inline">No approved reviews yet.</div>';$('#writeReviewBtn').onclick=()=>ShopApp.openLayer('reviewModal');$$('[data-lightbox]').forEach(b=>b.onclick=()=>{const c=$('#lightboxContent');c.innerHTML=`<img src="${esc(b.dataset.lightbox)}" alt="Review image">`;ShopApp.openLayer('lightboxModal')})}
  function mediaList(){return [...(product.media?.images||[]).map(src=>({type:'image',src})),...(product.media?.videos||[]).map(src=>({type:'video',src}))]}
  function renderGallery(){const list=mediaList(),main=$('#galleryMain'),thumbs=$('#galleryThumbs');if(!list.length){main.innerHTML='<div class="image-placeholder big">Step in Style</div>';thumbs.innerHTML='';return}activeMedia=Math.min(activeMedia,list.length-1);const m=list[activeMedia];main.innerHTML=m.type==='image'?`<button class="gallery-zoom" id="zoomMain"><img src="${esc(m.src)}" alt="${esc(product.name)}"><span>⌕ Tap to enlarge</span></button>`:videoHtml(m.src,'detail-video');thumbs.innerHTML=list.map((x,i)=>`<button class="gallery-thumb ${i===activeMedia?'active':''}" data-media="${i}">${x.type==='image'?`<img src="${esc(x.src)}" alt="">`:'<span>▶</span>'}</button>`).join('');$$('[data-media]').forEach(b=>b.onclick=()=>{activeMedia=Number(b.dataset.media);renderGallery()});$('#zoomMain')&&($('#zoomMain').onclick=()=>{const c=$('#lightboxContent');c.innerHTML=`<img src="${esc(m.src)}" alt="${esc(product.name)}">`;ShopApp.openLayer('lightboxModal')})}
  function variantHtml(){if(!product.variants?.length)return '';return `<div class="variant-area">${product.variants.map((v,i)=>`<label><span>${esc(v.name||'Option')}</span><select data-variant="${i}">${(v.values||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`).join('')}</div>`}

  async function render(){
    try{
      await ShopApp.ready;
      product=await StoreDB.getProduct(id,{preview});
      if(!product){$('#productPage').innerHTML='<div class="not-found"><div>🛍️</div><h1>Product not found</h1><p>This product may not be published yet.</p><a class="primary-btn" href="index.html#shop">Back to Shop</a></div>';return}
      if(!preview)StoreDB.incrementView(product.id);
      document.title=`${product.name} | Step in Style`;
      const r=ShopApp.ratingInfo(product.id),discount=product.oldPrice>product.price?Math.round((product.oldPrice-product.price)/product.oldPrice*100):0,avail=product.stock!=='out'&&(product.qty===999||Number(product.qty)>0);
      $('#productPage').innerHTML=`${preview?'<div class="preview-banner">Admin Preview — customers only see this after publishing.</div>':''}<div class="breadcrumbs"><a href="index.html">Home</a><span>›</span><a href="index.html#shop">Shop</a><span>›</span><span>${esc(product.name)}</span></div><section class="product-detail-layout"><div><div id="galleryMain" class="gallery-main"></div><div id="galleryThumbs" class="gallery-thumbs"></div></div><div class="product-info"><span class="product-cat">${esc(product.category||'Product')}</span><h1>${esc(product.name)}</h1><button class="rating-jump" id="ratingJump">${r.count?`<span class="stars">${'★'.repeat(Math.round(r.avg))}</span> ${r.avg.toFixed(1)} (${r.count} reviews)`:'No reviews yet'}</button><p class="product-short">${esc(product.shortDescription||'')}</p><div class="detail-price"><strong>${money(product.price)}</strong>${product.oldPrice>product.price?`<del>${money(product.oldPrice)}</del><span>${discount}% OFF</span>`:''}</div><div class="availability ${product.stock}">${product.stock==='out'?'● Out of Stock':product.stock==='limited'?'● Limited Availability':product.stock==='coming'?'● Coming Soon':'● Available'}</div>${variantHtml()}<div class="qty-select"><span>Quantity</span><div><button id="qtyMinus">−</button><strong id="qtyValue">1</strong><button id="qtyPlus">+</button></div></div><div class="detail-actions"><button class="primary-btn big" id="buyNow" ${!avail?'disabled':''}>Buy Now</button><button class="outline-btn big" id="addCart" ${!avail?'disabled':''}>Add to Cart</button></div><a class="whatsapp-product" id="productWhatsApp" target="_blank">💬 Ask About This Product</a><div class="confidence-row"><span>💵 Cash on Delivery</span><span>🚚 Islandwide Delivery</span><span>💬 0719141519</span></div></div></section><section class="product-content"><nav class="product-tabs"><button class="active" data-tab="description">Description</button><button data-tab="reviews">Reviews (${r.count})</button><button data-tab="delivery">Delivery</button></nav><div class="tab-panel active" id="tab-description">${renderDescription(product)}</div><div class="tab-panel" id="tab-reviews"><div id="reviewSummary" class="review-summary"></div><div id="reviewsList"></div></div><div class="tab-panel" id="tab-delivery"><div class="delivery-card"><h3>Delivery & Payment</h3><p>Step in Style offers islandwide delivery across Sri Lanka. Payment is Cash on Delivery unless otherwise stated.</p><ul><li>Enter a reachable phone number at checkout.</li><li>Our team may contact you to confirm the order.</li><li>For help, call or WhatsApp <b>0719141519</b>.</li></ul></div></div></section><section class="related-section"><div class="section-head"><div><span class="section-kicker">MORE TO EXPLORE</span><h2>You may also like</h2></div></div><div id="relatedGrid" class="product-grid related-grid"></div></section>`;
      renderGallery();renderReviews();renderRelated();bindProduct();
    }catch(err){$('#productPage').innerHTML=`<div class="not-found"><div>⚙</div><h1>Store setup required</h1><p>${esc(err.message)}</p><a class="primary-btn" href="index.html">Back Home</a></div>`}
  }
  function renderRelated(){const db=ShopApp.getDB(),list=db.products.filter(p=>p.status==='published'&&p.id!==product.id&&(p.category===product.category||product.category==='')).slice(0,4),grid=$('#relatedGrid');if(!list.length){grid.closest('.related-section').classList.add('hidden');return}grid.innerHTML=list.map(p=>`<article class="mini-product"><a href="product.html?id=${encodeURIComponent(p.id)}">${p.media?.images?.[0]?`<img src="${esc(p.media.images[0])}" alt="${esc(p.name)}">`:'<div class="image-placeholder">Step in Style</div>'}<span>${esc(p.name)}</span><b>${money(p.price)}</b></a></article>`).join('')}
  function bindProduct(){let qty=1;$('#qtyMinus').onclick=()=>{qty=Math.max(1,qty-1);$('#qtyValue').textContent=qty};$('#qtyPlus').onclick=()=>{qty++;$('#qtyValue').textContent=qty};$('#addCart').onclick=()=>ShopApp.addToCart(product.id,qty);$('#buyNow').onclick=()=>ShopApp.startCheckout([{productId:product.id,qty}]);$('#productWhatsApp').href=`https://wa.me/94719141519?text=${encodeURIComponent(`Hi Step in Style,\n\nI'm interested in:\n${product.name}\n${location.href}\n\nCould you please provide more information?`)}`;$('#ratingJump').onclick=()=>{document.querySelector('[data-tab="reviews"]').click();document.querySelector('.product-content').scrollIntoView({behavior:'smooth'})};$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+b.dataset.tab))})}

  async function compressImage(file){if(!file.type.startsWith('image/'))throw Error('Please select image files only.');if(file.size>8*1024*1024)throw Error('An image is too large. Maximum size is 8 MB.');const bmp=await createImageBitmap(file),max=1400,scale=Math.min(1,max/bmp.width),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bmp.width*scale));canvas.height=Math.max(1,Math.round(bmp.height*scale));canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);const blob=await new Promise(r=>canvas.toBlob(r,'image/webp',0.8));return new File([blob],(file.name.replace(/\.[^.]+$/,'')||'review')+'.webp',{type:'image/webp'})}
  async function handleReviewImages(files){try{reviewImageFiles=[];for(const f of [...files].slice(0,5))reviewImageFiles.push(await compressImage(f));$('#reviewImagePreview').innerHTML=reviewImageFiles.map(f=>`<img src="${URL.createObjectURL(f)}" alt="Preview">`).join('')}catch(e){ShopApp.toast(e.message)}}
  async function handleReviewVideo(file){if(!file)return;try{if(!['video/mp4','video/webm'].includes(file.type))throw Error('Use MP4 or WebM video.');if(file.size>25*1024*1024)throw Error('Review video must be under 25 MB.');reviewVideoFile=file;$('#reviewVideoPreview').innerHTML=`<video src="${URL.createObjectURL(file)}" controls playsinline></video>`}catch(e){ShopApp.toast(e.message)}}
  function bindReview(){
    $$(`#starPicker button`).forEach(b=>b.onclick=()=>{const n=Number(b.dataset.rating);$('#reviewForm').elements.rating.value=n;$$('#starPicker button').forEach(x=>x.classList.toggle('selected',Number(x.dataset.rating)<=n))});
    $('#reviewImages').onchange=e=>handleReviewImages(e.target.files);$('#reviewVideo').onchange=e=>handleReviewVideo(e.target.files[0]);
    $('#reviewForm').onsubmit=async e=>{
      e.preventDefault();const f=new FormData(e.currentTarget),rating=Number(f.get('rating'));if(!rating)return ShopApp.toast('Please choose a star rating.');const button=e.currentTarget.querySelector('button[type=submit]');button.disabled=true;button.textContent='Uploading Review...';
      try{
        const draft=StoreDB.uid('REV'),images=[],videos=[];
        for(const file of reviewImageFiles)images.push(await StoreDB.uploadReviewMedia(draft,file));
        if(reviewVideoFile)videos.push(await StoreDB.uploadReviewMedia(draft,reviewVideoFile));
        await StoreDB.submitReview({productId:product.id,name:f.get('name').trim(),phone:f.get('phone').trim(),rating,text:f.get('text').trim(),media:{images,videos}});
        ShopApp.closeLayer('reviewModal');e.currentTarget.reset();reviewImageFiles=[];reviewVideoFile=null;$('#reviewImagePreview').innerHTML='';$('#reviewVideoPreview').innerHTML='';$$('#starPicker button').forEach(x=>x.classList.remove('selected'));ShopApp.toast('Review submitted. It will appear after admin approval.');
      }catch(err){ShopApp.toast(err.message)}finally{button.disabled=false;button.textContent='Submit Review for Approval'}
    }
  }
  document.addEventListener('DOMContentLoaded',()=>{render();bindReview()});
})();
